### PR TITLE
Hopefully this fixes the session issues with the deployment server

### PR DESCRIPTION
**Pull request by ColtTheKing**

### CODE REVIEW

**Comment by NathanBarber97** [comment]
Need to create an actual data folder in the same folder as application, and for the path ../data instead of /tmp

**Comment by NathanBarber97** [comment]
You should put a dummy file in the data folder so that it wont be ignored

**Comment by NathanBarber97** [comment]
I don't think it will work if you gitignore the file, to be honest it doesn't matter if its on there, shouldn't affect anything. But the path needs to be "../data" instead of just "/data", or it won't work. The idea is that the data folder should be one level up from public. As in, in the same file as public and application.

**Comment by ColtTheKing** [comment]
Fixed

**Pull request merged**
